### ISSUE TITLE
austrinken jungs, wir haben noch ne ganze flasche sekt

### ISSUE THREAD

**Issue by laila-rin** [RenateDOC/renate#7]

**Comment by Mehyar-ALS** [comment]
[<iframe src="https://giphy.com/embed/ORjfgiG9ZtxcQQwZzv" width="480" height="360" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/126bpm-dancingatclub-ORjfgiG9ZtxcQQwZzv">via GIPHY</a></p>](url)
